spring.application.name=shareplatform
server.port=${PORT:5000}

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/shareplatform}

# JWT Configurations
app.jwtSecret=${JWT_SECRET:supersecretkey123}
app.jwtExpirationMs=${JWT_EXPIRATION_MS:86400000}
